name: mobile_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  json_serializable: ^6.7.0
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  retrofit_generator: ^7.0.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  snackbar: ^1.0.2
  top_snackbar_flutter: ^3.0.0+1
  connectivity_plus: ^4.0.1
  custom_pop_up_menu: ^1.2.4
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  get: ^4.6.5
  timer_count_down: ^2.2.2
  flutter_html: ^3.0.0-beta.2
  animated_text_kit: ^4.2.2
  google_fonts: ^5.1.0
  dropdown_button2: ^2.3.7
  badges: ^3.1.1
  toggle_switch: ^2.1.0
  hive: any
  hive_flutter: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.4
  hive_generator: any
  flutter_lints: ^2.0.0

flutter:
  generate : true
  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/icon/